In [1]:
import pandas as pd

# set files path
sales1 = '/home/adalaber/Escritorio/project-da-promo-A-module-2-team-2/txt_csv.csv'
sales2 = '/home/adalaber/Escritorio/project-da-promo-A-module-2-team-2/exported_db_data.csv'
sales3 = '/home/adalaber/Escritorio/project-da-promo-A-module-2-team-2/xml_csv.csv'

print("*** Merging multiple csv files into a single pandas dataframe ***")

# merge files
dataFrame = pd.concat(
   map(pd.read_csv, [sales1, sales2, sales3]), ignore_index=True)
print(dataFrame)

*** Merging multiple csv files into a single pandas dataframe ***
        Unnamed: 0  index         Q3                 Q4  \
0              0.0    0.0      India  Bachelor’s degree
1              1.0    1.0  Indonesia    Master’s degree
2              2.0    2.0   Pakistan    Master’s degree
3              3.0    3.0     Mexico    Doctoral degree
4              4.0    4.0      India    Doctoral degree
...            ...    ...        ...                ...
233753    181807.0    NaN        NaN                NaN
233754    181808.0    NaN        NaN                NaN
233755    181809.0    NaN        NaN                NaN
233756    181810.0    NaN        NaN                NaN
233757    181811.0    NaN        NaN                NaN

                             Q5          Q6      Q8  \
0                         Other  5-10 years  Python
1       Program/Project Manager   20+ years  Python
2             Software Engineer   1-3 years  Python
3            Research Scientist   20+ years  Python
4                         Other   < 1 years  Python
...                         ...         ...     ...
233753                      NaN         NaN     NaN
233754                      NaN         NaN     NaN
233755                      NaN         NaN     NaN
233756                      NaN         NaN     NaN
233757                      NaN         NaN     NaN

                                                      Q11                 Q13  \
0                                                A laptop           2-5 times
1       A cloud computing platform (AWS, Azure, GCP, h...               Never
2                                                A laptop               Never
3       A cloud computing platform (AWS, Azure, GCP, h...  More than 25 times
4       A cloud computing platform (AWS, Azure, GCP, h...               Never
...                                                   ...                 ...
233753                                                NaN                 NaN
233754                                                NaN                 NaN
233755                                                NaN                 NaN
233756                                                NaN                 NaN
233757                                                NaN                 NaN

                                          Q15  ... Q10_Part_9 Q10_Part_10  \
0                                  5-10 years  ...        NaN         NaN
1                                    < 1 year  ...        NaN         NaN
2       I do not use machine learning methods  ...        NaN         NaN
3                                  5-10 years  ...        NaN         NaN
4                                 10-20 years  ...        NaN         NaN
...                                       ...  ...        ...         ...
233753                                    NaN  ...        NaN         NaN
233754                                    NaN  ...        NaN         NaN
233755                                    NaN  ...        NaN         NaN
233756                                    NaN  ...        NaN         NaN
233757                                    NaN  ...        NaN         NaN

       Q10_Part_11 Q10_Part_12 Q10_Part_13 Q10_Part_14 Q10_Part_15  \
0              NaN         NaN         NaN         NaN         NaN
1              NaN         NaN         NaN         NaN         NaN
2              NaN         NaN         NaN         NaN         NaN
3              NaN         NaN         NaN         NaN         NaN
4              NaN         NaN         NaN         NaN         NaN
...            ...         ...         ...         ...         ...
233753         NaN         NaN         NaN         NaN         NaN
233754         NaN         NaN         NaN         NaN         NaN
233755         NaN         NaN         NaN         NaN         NaN
233756         NaN         NaN         NaN         NaN         NaN
233757         NaN         NaN         NaN         NaN         NaN

       Q10_Part_16 Q10_OTHER                <data>
0              NaN       NaN                   NaN
1              NaN       NaN                   NaN
2              NaN       NaN                   NaN
3              NaN       NaN                   NaN
4              NaN       NaN                   NaN
...            ...       ...                   ...
233753         NaN       NaN      <time>255</time>
233754         NaN       NaN      <age>18-21</age>
233755         NaN       NaN  <gender>Man</gender>
233756         NaN       NaN                </row>
233757         NaN       NaN               </data>

[233758 rows x 46 columns]